version: '3'

services:
   cassandra-1:
      hostname: cassandra-1
      image: cassandra
      command: /bin/bash -c "sleep 1 && /docker-entrypoint.sh cassandra -f"
      expose:
        - 7000
        - 7001
        - 9042
        - 9160

   cassandra-2:
      hostname: cassandra-2
      image: cassandra
      command: /bin/bash -c "sleep 30 && /docker-entrypoint.sh cassandra -f"
      links:
        - cassandra-1:seed
      depends_on:
        - cassandra-1
      expose:
        - 7000
        - 7001
        - 9042
        - 9160
      environment:
         - CASSANDRA_SEEDS=seed

   demo-app:
      build: 
         context: .
         dockerfile: Dockerfile-app
      hostname: demo-app
      image: cassandra-app-demo
      command: /bin/bash -c "sleep 90 && java -Djava.security.egd=file:/dev/./urandom -jar app.jar"
      links:
         - cassandra-1
         - cassandra-2
      depends_on:
         - cassandra-1
         - cassandra-2
      ports:
         - 10001:8080
      environment:
         - SPRING_DATA_CASSANDRA_CONTACT_POINTS=cassandra-1

        


